/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RailwayTicket;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;

public class RailwayTicket extends javax.swing.JFrame {

    /**
     * Creates new form RailwayTicket
     */
    public RailwayTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 10, true));
        jPanel1.setFont(new java.awt.Font("Calibri", 1, 90)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        jLabel1.setText("TRAIN TICKETING SYSTEM");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 90)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(2738, 2738, 2738))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(639, 639, 639))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 10));

        jRadioButton2.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton2.setText("Economy");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton3.setText("First Class");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel4.setText("Ticket Type");

        jRadioButton4.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton4.setText("Single");

        jRadioButton5.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton5.setText("Return");

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel5.setText("Adult");

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel6.setText("Child");

        jRadioButton6.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton6.setText("Yes");

        jRadioButton7.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel7.setText("Destination");

        jComboBox1.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mombasa", "Mariakani", "Miasenyi", "Voi", "Mtito Andei" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jLabel5))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jRadioButton7)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13)
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 10));

        jLabel8.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel8.setText("SubTotal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel10.setText("Tax");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel12.setText("Total");

        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButton1.setText("Total");
        jButton1.setMaximumSize(new java.awt.Dimension(89, 33));
        jButton1.setMinimumSize(new java.awt.Dimension(89, 33));
        jButton1.setPreferredSize(new java.awt.Dimension(89, 33));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextPane8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane8.setViewportView(jTextPane8);

        jTextPane9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane9.setViewportView(jTextPane9);

        jTextPane10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane10.setViewportView(jTextPane10);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 255, 0)));

        jLabel14.setBackground(new java.awt.Color(102, 0, 51));
        jLabel14.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel14.setText("Class");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel15.setBackground(new java.awt.Color(102, 0, 102));
        jLabel15.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel15.setText("Ticket Type");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel16.setBackground(new java.awt.Color(102, 0, 102));
        jLabel16.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel16.setText("Adult");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel17.setBackground(new java.awt.Color(102, 0, 102));
        jLabel17.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel17.setText("Child");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel18.setText("Date");

        jLabel19.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel19.setText("From");

        jLabel20.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel20.setText("To");

        jLabel21.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel21.setText("Time");

        jLabel22.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel22.setText("Ticket No");

        jLabel23.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel23.setText("Price");

        jLabel24.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jLabel24.setText("Route");

        jComboBox2.setFont(new java.awt.Font("Wide Latin", 1, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any" }));

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(381, 381, 381))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 93, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(372, 372, 372))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 5));

        jLabel36.setFont(new java.awt.Font("Wide Latin", 1, 8)); // NOI18N
        jLabel36.setText("WE VALUE OUR CUSTOMERS.WE INVITE YOU TO COME BACK AGAIN.THANK YOU");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(49, 49, 49)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(268, 268, 268))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.getContentPane().setBackground(Color.blue);       
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

jLabel27.setText(null);        
jLabel31.setText(null); 
jLabel29.setText(null); 
jLabel26.setText(null); 
jLabel25.setText(null); 
jLabel33.setText(null); 
jLabel34.setText(null); 
jLabel32.setText(null); 
jLabel28.setText(null);
jLabel30.setText(null); 
jTextPane10.setText(null); 
jTextPane8.setText(null); 
jTextPane9.setText(null); 

       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        //System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Calendar timer=Calendar.getInstance();
    timer.getTime();
SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
    jLabel32.setText(tTime.format(timer.getTime()));
    
    SimpleDateFormat tdate=new SimpleDateFormat("dd:MM:yyyy");
    jLabel34.setText(tdate.format(timer.getTime()));
    
    jLabel25.setText("Nairobi");// From
    jLabel33.setText((String)jComboBox1.getSelectedItem()+"");   //to
    
    int num1;
    String q1="";
    num1=3000 + (int)(Math.random()*5000);
    q1 +=num1 + 3000;
    jLabel28.setText(q1);
   // jLabel24.setText("ANY");
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
double tax=16;
double MilesK233=500;
double MilesK329=800;
double MilesK383=1000;
double MilesK449=1200;
double MilesK488=1500;
double totalCost , fclass=1500;


if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*MilesK233)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK233+totalCost));
    //String myString=Double.toString(totalCost);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }//GEN-LAST:event_jButton1MouseClicked
else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
  
    
      totalCost=(tax*MilesK233*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK233+totalCost)*2);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }                   
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*MilesK233)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK233+totalCost)/2));
     jTextPane9.setText(Total);
        //jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");

    }           

else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
    
      totalCost=(tax*MilesK233*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK233+totalCost)*2)/2);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 
    }            
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
   
      totalCost=(tax*MilesK329)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK329+totalCost);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }                                     
else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
  
      totalCost=(tax*MilesK329*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK329+totalCost)*2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }                   
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
  
      totalCost=(tax*MilesK329)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK329+totalCost)/2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }           

else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
  
      totalCost=(tax*MilesK329*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK329+totalCost)*2)/2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }           
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*MilesK383)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK383+totalCost);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }                                     
else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*MilesK383*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK383+totalCost)*2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }                   
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
   
      totalCost=(tax*MilesK383)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK383+totalCost)/2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }           

else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
   
      totalCost=(tax*MilesK383*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK383+totalCost)*2)/2);
      jTextPane9.setText(Total);
        //jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }            
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
    
      totalCost=(tax*MilesK449)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK449+totalCost);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel30.setText(Total);
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }                                     
else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
   
      totalCost=(tax*MilesK449*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK449+totalCost)*2);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }                   
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
  
      totalCost=(tax*MilesK449)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK449+totalCost)/2);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
    }           

else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
  
      totalCost=(tax*MilesK449*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK449+totalCost)*2)/2);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }            
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
    
      totalCost=(tax*MilesK488)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK488+totalCost);
    jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");

    }                                     
else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
   
      totalCost=(tax*MilesK488*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK488+totalCost)*2);
      jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }                   
else if ((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
   
      totalCost=(tax*MilesK488)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK488+totalCost)/2);
     jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 
    }           

else if ((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
   
      totalCost=(tax*MilesK488*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK488+totalCost)*2)/2);
     jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("ECOMOMY");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");

    }      
else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*(MilesK233+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233+fclass);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK233+fclass+totalCost);
     jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 


    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*MilesK233*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK233+totalCost)*2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }          

else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*(MilesK233+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233+fclass/2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK233+fclass+totalCost)/2);
       jTextPane9.setText(Total);
        jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");

    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mtito Andei"))
{
   
      totalCost=(tax*MilesK233*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK233*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK233+totalCost)*2)/2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 


    }            
else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
 
      totalCost=(tax*(MilesK329+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329+fclass);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK329+fclass+totalCost);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
   
      totalCost=(tax*MilesK329*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK329+totalCost)*2);
      jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 


    }          

else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
  
      totalCost=(tax*(MilesK329+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329+fclass/2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK329+fclass+totalCost)/2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 


    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Voi"))
{
   
      totalCost=(tax*MilesK329*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK329*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK329+totalCost)*2)/2);
       jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }      
else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*(MilesK383+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383+fclass);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK383+fclass+totalCost);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*MilesK383*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK383+totalCost)*2);
       jTextPane9.setText(Total);
       // jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }          

else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*(MilesK383+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383+fclass/2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK383+fclass+totalCost)/2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Miasenyi"))
{
  
      totalCost=(tax*MilesK383*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK383*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK383+totalCost)*2)/2);
      jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RUTURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }            
else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
  
      totalCost=(tax*(MilesK449+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449+fclass);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK449+fclass+totalCost);
      jTextPane9.setText(Total);
     //   jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
  
      totalCost=(tax*MilesK449*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK449+totalCost)*2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 

    }          

else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
   
      totalCost=(tax*(MilesK449+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449+fclass/2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK449+fclass+totalCost)/2);
       jTextPane9.setText(Total);
     //   jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mariakani"))
{
  
      totalCost=(tax*MilesK449*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK449*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK449+totalCost)*2)/2);
       jTextPane9.setText(Total);
    //    jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 
    }   
else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
  
      totalCost=(tax*(MilesK488+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488+fclass);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",MilesK488+fclass+totalCost);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton6.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
   
      totalCost=(tax*MilesK488*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK488+totalCost)*2);
      jTextPane9.setText(Total);
     //   jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("ONE");
        jLabel26.setText("NONE");
 
    }          

else if ((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
  
      totalCost=(tax*(MilesK488+fclass))/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488+fclass/2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",(MilesK488+fclass+totalCost)/2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("SINGLE");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 

    }    
else if ((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&(jRadioButton7.isSelected())&& jComboBox1.getSelectedItem().equals("Mombasa"))
{
  
      totalCost=(tax*MilesK488*2)/100;
      String sTax=String.format("KSH:%.2f",totalCost);
      jTextPane8.setText(sTax);
    String subTotal=String.format("KSH:%.2f",MilesK488*2);
    jTextPane10.setText(subTotal);
    String Total=String.format("KSH:%.2f",((MilesK488+totalCost)*2)/2);
       jTextPane9.setText(Total);
      //  jTextPane10.setText(Total);
        jLabel30.setText(Total);
        jLabel27.setText("FIRST CLASS");
        jLabel31.setText("RETURN");
        jLabel29.setText("NONE");
        jLabel26.setText("ONE");
 
    }  
    }
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new RailwayTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    // End of variables declaration//GEN-END:variables
}
